src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $note = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[Assert\LessThanOrEqual('today')]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_visite = null;

    #[ORM\Column(length: 100)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commentaire = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $reponse = null;

    #[ORM\Column(length: 32)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateVisite(): ?\DateTimeInterface
    {
        return $this->date_visite;
    }

    public function setDateVisite(\DateTimeInterface $date_visite): static
    {
        $this->date_visite = $date_visite;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(?string $reponse): static
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if (!$options['valider_avis']) {
            # The formulaire est nécessaire pour le client
            $builder
                ->add('note', ChoiceType::class, [
                    'choices'  => [
                        'Selectionner une note sur 5' => '',
                        '1' => '1',
                        '2' => '2',
                        '3' => '3',
                        '4' => '4',
                        '5' => '5',
                    ],
                    'required' => true,
                ])
                ->add('nom')
                ->add('date_visite', DateType::class, [
                    'widget' => 'single_text',
                ])
                ->add('titre')
                ->add('commentaire')
            ;
        }
        else {
            # Ceci est le formulaire nécessaire à l'employé pour valider l'avis
            $builder
                ->add('reponse')
                ->add('status', ChoiceType::class, [
                    'choices'  => [
                        'Accepté' => 'accepted',
                        'Refusé' => 'refused',
                    ],
                ])
            ;
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
            'valider_avis' => false,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AvisController extends AbstractController
{
    #[Route('/espace-pro/avis', name: 'app_avis_index', methods: ['GET'])]
    public function index(Request $request, AvisRepository $avisRepository): Response
    {
        $form = $this->createFormBuilder(null, ['csrf_protection' => false])
            ->setAction($this->generateUrl('app_avis_index'))
            ->setMethod('GET')
            ->add('showAll', CheckboxType::class, [
                'required' => false,
                'label_attr' => [
                    'class' => 'checkbox-switch',
                ],
                'label' => 'Montrer tous les avis'
            ])
            ->add('page', HiddenType::class, [
                'required'=> false,
            ])
            ->getForm();

        $form->handleRequest($request);
        $page = $request->query->get('page', 1);

        if ($form->isSubmitted() && $form->isValid())
        {
            $paginator = $avisRepository->getAvisPaginator($page, $form->getData()['showAll']);
        } else {
            $paginator = $avisRepository->getAvisPaginator($page);
        }
        $next = count($paginator) < AvisRepository::AVIS_PER_PAGE * $page + 1 ? 0 : $page + 1;

        return $this->render('avis/index.html.twig', [
            'avis' => $paginator,
            'form' => $form,
            'previous' => $page - 1,
            'next' => $next,
        ]);
    }

    #[Route('/espace-pro/avis/new', name: 'app_avis_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avis = new Avis();
        $avis->setStatus("accepted");
        $form = $this->createForm(AvisType::class, $avis);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avis);
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/new.html.twig', [
            'avis' => $avis,
            'form' => $form,
        ]);
    }

    #[Route('/espace-pro/avis/{id}', name: 'app_avis_show', methods: ['GET'])]
    public function show(Avis $avis): Response
    {
        return $this->render('avis/show.html.twig', [
            'avis' => $avis,
        ]);
    }

    #[Route('/espace-pro/avis/{id}/edit', name: 'app_avis_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Avis $avis, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvisType::class, $avis, array(
            'valider_avis' => true,
        ));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
//            if ($avis->getStatus() == 'accepted')
//            {
//               # TODO: invalidate cache
//            }

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/edit.html.twig', [
            'avis' => $avis,
            'form' => $form,
        ]);
    }

    #[Route('/espace-pro/avis/{id}', name: 'app_avis_delete', methods: ['POST'])]
    public function delete(Request $request, Avis $avis, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avis->getId(), $request->request->get('_token'))) {
            $entityManager->remove($avis);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/donner-son-avis', name: 'app_avis_client', methods: ['GET', 'POST'])]
    public function new_client(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avis = new Avis();
        $avis->setStatus("submitted");
        $form = $this->createForm(AvisType::class, $avis);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avis);
            $entityManager->flush();

            return $this->redirectToRoute('app_homepage', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/new_client.html.twig', [
            'avis' => $avis,
            'form' => $form,
        ]);
    }

    public function derniers_avis(AvisRepository $avisRepository, ?int $max = 4): Response
    {
        return $this->render('avis/_derniers_avis.html.twig', [
            'avis' => $avisRepository->findAllByStatus('accepted', $max),
        ]);
    }
}

templates/avis/_delete_form.html.twig
<form method="post" action="{{ path('app_avis_delete', {'id': avi.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet avis?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avi.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/avis/_derniers_avis.html.twig
<div class="row p-3">
{% for avi in avis|slice(0,4) %}
    <div class="col-md-3">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title fw-bold">{{ avi.nom }}</h5>
                <span>
                    {% for i in range(1, 5) %}
                        {% if i <= avi.note %}
                            <i class="bi bi-star-fill"></i>
                        {% else %}
                            <i class="bi bi-star"></i>
                        {% endif %}
                    {% endfor %}
                </span>
            </div>
            <div class="card-body">
                <p class="card-text" style="min-height: 8em;">
                    <strong>{{ avi.titre }}</strong><br>
                    {{ avi.commentaire }}
                </p>
                <p class="card-subtitle">visite le {{ avi.dateVisite ? avi.dateVisite|date('Y-m-d') : '' }}</p>
            </div>
        </div>
    </div>
{% else %}
    <div class="col-12 text-center">
        Pas encore d'avis enregistrés
    </div>
{% endfor %}
</div>
<div class="d-md-flex justify-content-center p-3">
    {% set hasAvis = avis|length > 0 %}
    {% if hasAvis %}
    <button type="button" data-bs-toggle="modal" data-bs-target="#avisModal" class="btn btn-primary btn-lg me-2">Voir plus d'avis</button>
    {% endif %}
    <a class="btn btn-primary btn-lg {% if hasAvis %}ms-2{% endif %}" href="{{ path('app_avis_client') }}" role="button">Laisser votre avis</a>
</div>
{% if hasAvis %}
<div class="modal fade" id="avisModal" tabindex="-1" aria-labelledby="avisModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Nos Avis</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="word-wrap: break-word;">
                {% for avi in avis %}
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title fw-bold">{{ avi.nom }}</h5>
                        <span>
                            {% for i in range(1, 5) %}
                                {% if i <= avi.note %}
                                    <i class="bi bi-star-fill"></i>
                                {% else %}
                                    <i class="bi bi-star"></i>
                                {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                    <div class="d-flex justify-content-between">
                        <strong>{{ avi.titre }}</strong>
                        <span>le {{ avi.dateVisite ? avi.dateVisite|date('Y-m-d') : '' }}</span>
                    </div>
                    <p>
                        {{ avi.commentaire }}
                    </p>
                    <br>
                    {% if avi.reponse %}
                        <strong>Réponse:</strong>
                        <p>
                            {{ avi.reponse }}
                        </p>
                    {% endif %}
                    <hr>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

templates/avis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% if back_button|default(false) %}
        <a href="{{ path('app_avis_index') }}" class="btn btn-danger me-3" style="width: 120px;">Annuler</a>
    {% endif %}
    <button class="btn btn-primary" style="width: 120px;">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/avis/_form_client.html.twig
{{ form_start(form) }}
<div class="row g-3 p-3">
    <div class="col-md-12">
        {{ form_row(form.note, { label: 'Quelle note donneriez-vous à votre expérience ?'}) }}
    </div>
    <div class="col-md-12">
        {{ form_row(form.nom, { label: 'Quel est votre nom ?'}) }}
    </div>
    <div class="col-md-12">
        {{ form_row(form.date_visite, { label: 'À quelle date êtes-vous venu ?'}) }}
    </div>
    <div class="col-md-12">
        {{ form_row(form.titre, { label: 'Donnez un titre à votre avis'}) }}
    </div>
    <div class="col-md-12">
        {{ form_row(form.commentaire, { label: 'Ajoutez votre commentaire'}) }}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Envoyer votre avis</button>
    </div>

</div>
{{ form_end(form) }}

templates/avis/edit.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Avis Client{% endblock %}

{% block content %}
    <h1 class="text-center p-3">Avis Client</h1>
    <div>
        <span>Nom du client: {{ avis.nom }}</span>
    </div>
    <div>
        <span>Date de la visite: {{ avis.dateVisite ? avis.dateVisite|date('Y-m-d') : '' }}</span>
    </div>
    <div>
        <span>Titre: {{ avis.titre }}</span>
    </div>
    <div>
        <span>Message:</span>
        <p>{{ avis.commentaire }}</p>
    </div>

    {{ include('avis/_form.html.twig', { button_label: 'Valider', back_button: true}) }}

{% endblock %}

templates/avis/index.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Liste des avis{% endblock %}
{% set queryParams = app.request.query.all %}
{% block content %}
    <script>
        window.onload = function () {
            const pageField = document.querySelector('#form_showAll')
            const form = document.querySelector('form');
            pageField.addEventListener('change', function () {
                pageField.value = '1';
                form.submit();
            });
        }
    </script>
    <h1 class="text-center p-3">Liste des avis</h1>
    <div class="row justify-content-around d-flex align-content-center">
        <div class="col-6">
            {{ form_start(form) }}
            {{ form_widget(form, {'label': 'Montrer tous les avis'}) }}
            {{ form_end(form) }}
        </div>
        <div class="col-6 text-end">
            <a href="{{ path('app_avis_new') }}" class="btn btn-primary">Ajouter un avis</a>
        </div>
    </div>
    {% set map_label = {
        'submitted': 'A valider',
        'accepted': 'Publié',
        'refused': 'Refusé'
    } %}
    <div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Nom client</th>
                <th scope="col">Note</th>
                <th scope="col">Date visite</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for avi in avis %}
                <tr>
                    <th scope="row">{{ map_label[avi.status]|default('-') }}</th>
                    <td> {{ avi.nom }}</td>
                    <td>{{ avi.note }}/5</td>
                    <td>{{ avi.dateVisite ? avi.dateVisite|date('Y-m-d') : '' }}</td>
                    <td class="d-md-flex justify-content-md-end">
                        <a href="{{ path('app_avis_edit', {'id': avi.id}) }}" class="btn btn-primary me-2">Ouvrir</a>
                        {{ include('avis/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Pas d'avis</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="d-flex justify-content-between">
        <div>
        {% if previous >= 1 %}
            <a href="{{ path('app_avis_index', queryParams|merge({page: previous})) }}" class="btn btn-primary">Précedente</a>
        {% endif %}
        </div>
        <div>
        {% if next != 0 %}
            <a href="{{ path('app_avis_index', queryParams|merge({page: next})) }}" class="btn btn-primary">Suivante</a>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/avis/new.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Nouvel Avis Client{% endblock %}

{% block content %}
    <h1 class="text-center p-3">Nouvel Avis Client</h1>

    {{ include('avis/_form.html.twig', { button_label: 'Créer', back_button: true}) }}

{% endblock %}

templates/avis/new_client.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Laisser un avis{% endblock %}

{% block main %}
    <main>
        <div class="container p-3 rounded">
            <div class="row fw-bolder align-items-stretch rounded" style="background-color: #f0c542; color: #24393e;">
                <div class="col-sm-4 py-3 py-lg-2 rounded d-flex align-items-center justify-content-center flex-column order-1 order-sm-0" style="background-color: #24393e; color: #f0c542;">
                    <div>
                        <h2 class="d-inline-block ps-3 pb-3">Dites nous, comment s'est passé votre visite ?</h2>
                    </div>
                    <div>
                        <img src="{{ asset('assets/logo-garage.png') }}" style="width: 120px;"/>
                    </div>
                </div>
                <div class="col-sm-8 rounded" >
                    {{ include('avis/_form_client.html.twig') }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/avis/show.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
    <h1>Avis</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avis.id }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ avis.note }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ avis.nom }}</td>
            </tr>
            <tr>
                <th>Date_visite</th>
                <td>{{ avis.dateVisite ? avis.dateVisite|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ avis.titre }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ avis.commentaire }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ avis.reponse }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ avis.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_avis_index') }}">back to list</a>

    <a href="{{ path('app_avis_edit', {'id': avis.id}) }}">edit</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}