src/Entity/Horaires.php
<?php

namespace App\Entity;

use App\Repository\HorairesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HorairesRepository::class)]
class Horaires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $position = null;

    #[ORM\Column(length: 10)]
    private ?string $nom_jour = null;

    #[ORM\Column]
    private ?bool $ouverture = null;

    #[ORM\Column(type: Types::JSON)]
    private array $horaires = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getNomJour(): ?string
    {
        return $this->nom_jour;
    }

    public function setNomJour(string $nom_jour): static
    {
        $this->nom_jour = $nom_jour;

        return $this;
    }

    public function isOuverture(): ?bool
    {
        return $this->ouverture;
    }

    public function setOuverture(bool $ouverture): static
    {
        $this->ouverture = $ouverture;

        return $this;
    }

    public function getHoraires(): array
    {
        return $this->horaires;
    }

    public function setHoraires(array $horaires): static
    {
        $this->horaires = $horaires;

        return $this;
    }

    public function getHorairesFromIndex(int $index): ?string
    {
        if (count($this->horaires) < $index + 1) {
            return null;
        }
        return $this->horaires[$index];
    }

}

src/Form/HorairesType.php
<?php

namespace App\Form;

use App\Entity\Horaires;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Exception\UnexpectedTypeException;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

#class HorairesType extends AbstractType
class HorairesType extends AbstractType implements DataMapperInterface
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            # ->add('position')
            # ->add('nom_jour')
            ->add('ouverture')
            # ->add('horaires')
            ->add('morning_open', TimeType::class, [
                'input' => 'string',
                'minutes' => [0, 30],
            ])
            ->add('morning_close', TimeType::class, [
                'input' => 'string',
                'minutes' => [0, 30],
            ])
            ->add('afternoon_open', TimeType::class, [
                'input' => 'string',
                'minutes' => [0, 30],
            ])
            ->add('afternoon_close', TimeType::class, [
                'input' => 'string',
                'minutes' => [0, 30],
            ])
            ->setDataMapper($this)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Horaires::class,
        ]);
    }


    /**
     * @param Horaires|null $viewData
     */
    public function mapDataToForms($viewData, \Traversable $forms): void
    {
        // there is no data yet, so nothing to prepopulate
        if (null === $viewData) {
            return;
        }

        // invalid data type
        if (!$viewData instanceof Horaires) {
            throw new UnexpectedTypeException($viewData, Horaires::class);
        }

        /** @var FormInterface[] $forms */
        $forms = iterator_to_array($forms);
        // initialize form field values
        $forms['morning_open']->setData($viewData->getHorairesFromIndex(0));
        $forms['morning_close']->setData($viewData->getHorairesFromIndex(1));
        $forms['afternoon_open']->setData($viewData->getHorairesFromIndex(2));
        $forms['afternoon_close']->setData($viewData->getHorairesFromIndex(3));
        $forms['ouverture']->setData(($viewData->isOuverture()));
    }

    /**
     * @param Horaires|null $viewData
     */
    public function mapFormsToData(\Traversable $forms, &$viewData): void
    {
        /** @var FormInterface[] $forms */
        $forms = iterator_to_array($forms);

        $viewData->setOuverture($forms['ouverture']->getData());
        $viewData->setHoraires([
            $forms['morning_open']->getData(),
            $forms['morning_close']->getData(),
            $forms['afternoon_open']->getData(),
            $forms['afternoon_close']->getData(),
        ]);
    }
}

src/Controller/HorairesController.php
<?php

namespace App\Controller;

use App\Entity\Horaires;
use App\Form\HorairesType;
use App\Form\HorairesListType;
use App\Repository\HorairesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class HorairesController extends AbstractController
{
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/espace-pro/horaires', name: 'app_horaires_edit', methods: ['GET', 'POST'])]
    public function index2(Request $request, HorairesRepository $horairesRepository, EntityManagerInterface $entityManager): Response
    {
        $horaires = $horairesRepository->findAll();

        $form = $this->createForm(HorairesListType::class, [
            'horaires' => $horaires,
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_horaires_edit', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('horaires/edit.html.twig', [
            'list_horaires' => $horaires,
            'form' => $form,
        ]);
    }

    public function horaires(HorairesRepository $horairesRepository): Response
    {
        return $this->render('horaires/_horaires.html.twig', [
            'horaires' => $horairesRepository->findAll(),
        ]);
    }
}

templates/horaires/_delete_form.html.twig
<form method="post" action="{{ path('app_horaires_delete', {'id': horaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ horaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/horaires/_horaires.html.twig
{% for horaire in horaires %}
    <div class="d-flex align-items-center justify-content-center">
        <div class="text-start" style="min-width: 140px;">{{ horaire.nomJour }}</div>
        <div class="pb-1">
            {% if horaire.ouverture == false %}
                <div>
                    Fermé
                </div>
            {% else %}
                <div>
                {% for slot in horaire.horaires|batch(2, 'Fermé') %}
                    {% if slot[loop.index] != '00:00:00' %}
                        <div>
                            {{ slot ? slot|map(p => "#{p|slice(0, 5)}")|join(' à ') : ''}}
                        </div>
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% else %}
    <div>Pas d'horaires enregistrées</div>
{% endfor %}

templates/horaires/edit.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Editer les horaires{% endblock %}

{% block content %}
    <script>
        window.onload = function () {

        }
    </script>
    <h1 class="text-center p-3">Editer les horaires</h1>
    <div class="alert alert-primary" role="alert">
        Pour éditer les horaires, vous pouvez cocher les jours où vous êtes ouvert.
        La première ligne de chaque jour vous permet de gérer la première ouverture. Si vous êtes ouvert non-stop,
        vous pouvez configurer seulement la première.
        Si la ligne contient deux fois 00:00, celle-ci est considéré comme fermée.
    </div>

    {{ form_start(form) }}

    <div class="horaires">
        {% for horaire in form.horaires %}
            <div class="row">
                <div class="col-md-2 d-flex align-items-center">
            {{ form_errors(horaire) }}
            {{ form_row(horaire.ouverture, {label: list_horaires[loop.index0].nomJour}) }}
                </div>
                <div class="col-auto">
                    <div class="row py-2">
                    {% for slot in horaire.children %}
                        {% if slot is not same as (horaire.ouverture) %}
                        <div class="col-md-6 py-1">
                        {{ form_widget(slot) }}
                        </div>
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="text-end">
        <button class="btn btn-primary me-3" style="width: 140px;">{{ button_label|default('Sauvegarder') }}</button>
    </div>
    {{ form_end(form) }}

{% endblock %}

templates/horaires/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Horaires index{% endblock %}

{% block body %}
    <h1>Horaires index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Jour</th>
                <th>Horaires</th>
            </tr>
        </thead>
        <tbody>
        {% for horaire in horaires %}
            <tr>
                <td>{{ horaire.nomJour }}</td>
                <td>
                    {% if horaire.ouverture == false %}
                        Fermé
                    {% else %}
                        {% for slot in horaire.horaires|batch(2, 'Fermé') %}
                            {% if loop.first == false %}
                                <br/>
                            {% endif %}
                            {% if slot[loop.index] != '00:00:00' %}
                                {{ slot ? slot|map(p => "#{p|slice(0, 5)}")|join(' à ') : ''}}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Pas d'horaires enregistrées</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}