src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 128)]
    private ?string $email = null;

    #[ORM\Column(length: 15)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $sujet = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column]
    private ?bool $lu = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $sent_at = null;

    #[ORM\PrePersist]
    public function setSentAtValue(): void
    {
        $this->sent_at = new \DateTimeImmutable();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(string $sujet): static
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function isLu(): ?bool
    {
        return $this->lu;
    }

    public function setLu(bool $lu): static
    {
        $this->lu = $lu;

        return $this;
    }

    public function getSentAt(): ?\DateTimeImmutable
    {
        return $this->sent_at;
    }

    public function setSentAt(\DateTimeImmutable $sent_at): static
    {
        $this->sent_at = $sent_at;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('email')
            ->add('telephone', TelType::class)
            ->add('sujet')
            ->add('message')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessageController extends AbstractController
{
    #[Route('/espace-pro/messages', name: 'app_message_index', methods: ['GET'])]
    public function index(Request $request, MessageRepository $messageRepository): Response
    {
        $form = $this->createFormBuilder(null, ['csrf_protection' => false])
            ->setAction($this->generateUrl('app_message_index'))
            ->setMethod('GET')
            ->add('showUnread', CheckboxType::class, [
                'required' => false,
                'label_attr' => [
                    'class' => 'checkbox-switch',
                ],
                'label' => 'Masquer messages lus'
            ])
            ->add('page', HiddenType::class, [
                'required'=> false,
            ])
            ->getForm();

        $form->handleRequest($request);
        $page = $request->query->get('page', 1);

        if ($form->isSubmitted() && $form->isValid())
        {
            $paginator = $messageRepository->getMessagePaginator($page, $form->getData()['showUnread']);
        } else {
            $paginator = $messageRepository->getMessagePaginator($page);
        }
        $next = count($paginator) < MessageRepository::MESSAGES_PER_PAGE * $page + 1 ? 0 : $page + 1;

        return $this->render('message/index.html.twig', [
            'messages' => $paginator,
            'form' => $form,
            'previous' => $page - 1,
            'next' => $next,
        ]);
    }

    #[Route('/contact', name: 'app_message_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setLu(false);
            $entityManager->persist($message);
            $entityManager->flush();

            return $this->redirectToRoute('app_homepage', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('message/new.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }

    #[Route('/espace-pro/messages/{id}', name: 'app_message_show', methods: ['GET'])]
    public function show(Message $message, EntityManagerInterface $entityManager): Response
    {
        $message->setLu(true);
        $entityManager->persist($message);
        $entityManager->flush();
        return $this->render('message/show.html.twig', [
            'message' => $message,
        ]);
    }

    #[Route('/espace-pro/messages/{id}', name: 'app_message_delete', methods: ['POST'])]
    public function delete(Request $request, Message $message, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $entityManager->remove($message);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_message_index', [], Response::HTTP_SEE_OTHER);
    }

    public function contact_voiture(string $sujet): Response
    {
        $message = new Message();
        $message->setSujet($sujet);
        $form = $this->createForm(MessageType::class, $message, [
            'action' => $this->generateUrl('app_message_new'),
        ]);

        return $this->render('message/_contact_vehicule_form.html.twig', [
            'message' => $message,
            'form' => $form,
        ]);
    }
}

templates/message/_contact_vehicule_form.html.twig
{{ form_start(form) }}
<div class="row g-3 p-3">
    <div class="col-md-6">
        <div class="row">
            {{ form_row(form.nom, { label: 'Votre nom'}) }}
        </div>
        <div class="row">
            {{ form_row(form.telephone, { label: 'Votre numéro de téléphone'}) }}
        </div>
        <div class="row">
            {{ form_row(form.email, { label: 'Votre adresse email'}) }}
        </div>
    </div>
    <div class="col-md-6 big-textarea">
        {{ form_row(form.message, { label: 'Votre message'}) }}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </div>
    <input type="hidden" name="message[sujet]" value="{{ field_value(form.sujet) }}"/>
    {% do form.sujet.setRendered() %}

</div>
{{ form_end(form) }}

templates/message/_delete_form.html.twig
<form method="post" action="{{ path('app_message_delete', {'id': message.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce message?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/message/_form.html.twig
{{ form_start(form) }}
<div class="row g-3 p-3">
    <div class="col-md-6">
        {{ form_row(form.nom, { label: 'Votre nom'}) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.telephone, { label: 'Votre numéro de téléphone'}) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.email, { label: 'Votre adresse email'}) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.sujet, { label: 'Sujet de votre demande'}) }}
    </div>
    <div class="col-md-12">
        {{ form_row(form.message, { label: 'Votre message'}) }}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </div>
</div>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Edit Message{% endblock %}

{% block body %}
    <h1>Edit Message</h1>

    {{ include('message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_message_index') }}">back to list</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}

templates/message/index.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Liste des messages{% endblock %}

{% set queryParams = app.request.query.all %}
{% block content %}
    <script>
        window.onload = function () {
            const pageField = document.querySelector('#form_showUnread')
            const form = document.querySelector('form');
            pageField.addEventListener('change', function () {
                pageField.value = '1';
                form.submit();
            });
        }
    </script>

    <h1 class="text-center p-3">Liste des messages</h1>
    <div class="row">
        <div class="col-6">
            {{ form_start(form) }}
            {{ form_widget(form, {'label': 'Masquer les messages lus'}) }}
            {{ form_end(form) }}
        </div>
    </div>
{#    <div class="form-check form-switch justify-content-end">#}
{#        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">#}
{#        <label class="form-check-label" for="flexSwitchCheckDefault">Masques les messages lus</label>#}
{#    </div>#}
    <div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Date</th>
                <th scope="col">Nom client</th>
                <th scope="col">Sujet</th>
                <th scope="col"> </th>
            </tr>
            </thead>
            <tbody>
            {% for message in messages %}
                <tr>
                    <th scope="row">{{ message.lu ? 'Lu' : 'Non-lu' }}</th>
                    <td>{{ message.sentAt ? message.sentAt|date('Y-m-d H:i', 'Europe/Paris') : '' }}</td>
                    <td>{{ message.nom }}</td>
                    <td>{{ message.sujet }}</td>
                    <td class="d-md-flex justify-content-md-end">
                        <a href="{{ path('app_message_show', {'id': message.id}) }}" class="btn btn-primary me-2">Ouvrir</a>
                        {{ include('message/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">Pas de messages</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-between">
        <div>
            {% if previous >= 1 %}
                <a href="{{ path('app_message_index', queryParams|merge({page: previous})) }}" class="btn btn-primary">Précedente</a>
            {% endif %}
        </div>
        <div>
            {% if next != 0 %}
                <a href="{{ path('app_message_index', queryParams|merge({page: next})) }}" class="btn btn-primary">Suivante</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/message/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Contactez notre atelier{% endblock %}

{% block main %}
    <main>
        <div>
            <h1 class="text-center">Contactez notre atelier</h1>
        </div>
        <div class="container p-3 rounded">
            <div class="row fw-bolder align-items-stretch rounded" style="background-color: #f0c542; color: #24393e;">
                <div class="col-sm-4 py-3 py-lg-2 rounded d-flex align-items-center justify-content-center flex-column order-1 order-sm-0" style="background-color: #24393e; color: #f0c542;">
                    <div>
                        <img src="{{ asset('assets/logo-garage.png') }}" style="width: 120px;"/>
                    </div>
                    <div>
                        <i class="bi bi-telephone"></i><span class="d-inline-block pb-3 ps-3">05 71 52 01 86</span>
                    </div>
                    <div class="text-center">
                        <i class="bi bi-geo-alt"></i><span class="d-inline-block ps-3">74 rue de Georges</span><br>
                        <span>31000 Toulouse</span>
                    </div>
                    <div>
                        <i class="bi bi-envelope"></i><span class="d-inline-block ps-3 pt-3">contact@garagevparrot.fr</span>
                    </div>
                </div>
                <div class="col-sm-8 rounded" >
                    {{ include('message/_form.html.twig') }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/message/show.html.twig
{% extends 'layout_pro.html.twig' %}

{% block title %}Message {{ message.sujet }}{% endblock %}

{% block content %}
    <h1 class="text-center p-3">Message client</h1>
    <div class="text-start">
        <ul>
            <li>Nom: {{ message.nom }}</li>
            <li>Envoyé à: {{ message.sentAt ? message.sentAt|date('Y-m-d H:i:s', 'Europe/Paris') : '' }}</li>
            <li>Mail: {{ message.email }}</li>
            <li>Numéro de téléphone: {{ message.telephone }}</li>
            <li><strong>Sujet: {{ message.sujet }}</strong></li>
        </ul>
        <hr>
        <p>{{ message.message }}</p>
        <hr>
    </div>
    <div class="d-flex justify-content-between">
        <a href="{{ path('app_message_index') }}" class="btn btn-primary">Retour aux messages</a>
        {{ include('message/_delete_form.html.twig') }}
    </div>

{% endblock %}